#ifndef __CONFIG_H_452C
#define __CONFIG_H_452C

#define CONFIG_ARV452C		1
#define CONFIG_ARCADYAN		"ARV452CPW"

#define CONFIG_SYS_MAX_RAM	32*1024*1024
#define CONFIG_USE_DDR_PSC_32   1
#define	CONFIG_SYS_PROMPT	"ARV452c => "
#define CONFIG_RMII		1
#define CONFIG_RTL8306_SWITCH	1
#define CONFIG_EBU_GPIO		0xf00

#define CONFIG_BUTTON_PORT0
#define CONFIG_BUTTON_PIN	11
#define CONFIG_BUTTON_LEVEL	0

#include "arcadyan-common.h"

#endif
